### ISSUE TITLE
unable to require 'databasedotcom' in project

### ISSUE THREAD

**Issue by gostrc** [heroku/databasedotcom#161]
I get the following error:

```active_support/core_ext/module/deprecation.rb:21:in `deprecate': uninitialized constant ActiveSupport::Deprecation (NameError)```

To fix this, you need to require 'active_support' right before.

**Comment by ckoppelman** [comment]
Is this in the pipeline to be fixed? It seems rather easy.

**Comment by ckoppelman** [comment]
Thanks.
