### ISSUE TITLE
Suggest this library be sun-setted in favor of restforce

### ISSUE THREAD

**Issue by dcarroll** [heroku/databasedotcom#184]
This repo is pretty well orphaned and has tons of outstanding pull requests and unresolved issues.  There is another ruby lib at https://github.com/ejholmes/restforce that seems more active and up to date.

**Comment by freeformz** [comment]
IMO: If we do this we should also release a new gem version that throws a deprecated warning as well.

**Comment by dcarroll** [comment]
Yes, good point.

On Thu, Oct 22, 2015 at 2:07 PM, Edward Muller <notifications@github.com>
wrote:

> IMO: If we do this we should also release a new gem version that throws a
> deprecated warning as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/databasedotcom/issues/184#issuecomment-150356577>
> .
>



-- 
Thanks,
Dave

**Comment by jadercorrea** [comment]
I haven't tried Restforce, but it looks good. Maybe we should deprecate this one. 
:+1: for deprecation warning.
